version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: f1_fantasy_league_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/f1_fantasy_league_db -schemas=public -user=postgres -password=password -connectRetries=5 migrate -validateMigrationNaming=true -X
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
volumes:
  db:
