name: Verify API Integration Tests

on:
  pull_request:
    paths:
      - "server/**"
      - "database/**"

defaults:
  run:
    working-directory: ./server

env:
  DATABASE_URL: postgresql://postgres:password@localhost:5433/f1_fantasy_league_db?schema=public

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm i
      - name: Test
        run: npm run test:integration
